#!/usr/bin/env python
from sense_hat import SenseHat
sense = SenseHat()

r = (255, 0, 0)
b = (0, 0, 255)
w = (255, 255, 255)

pixels = [
    r, r, r, r, r, w, w, b,
    b, b, b, w, r, w, r, w,
    w, w, w, w, r, b, b, w,
    r, r, r, r, r, r, r, r, 
    w, w, w, w, w, w, w, w,
    b, b, b, b, b, b, b, b, 
    b, w, r, w, b, w, r, w, 
    w, r, w, b, b, r, w, r, 
]
sense.set_pixels(pixels)
sense.clear()


